config/routes.rb
Rails.application.routes.draw do
  get "requests/edit", :to => "requests#index"
  get "requests/show", :to => "requests#index"
  get "requests/update", :to => "request#index"
  devise_scope :user do
    get "/users/sign_up",  :to => "requests#index"
  end

  devise_for :users
  resources :requests, only: [:index, :new, :create, :destroy, :update, :edit]
  resources :users, only: [:show]

  root "requests#index"

end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_login
  after_create :add_user_group

  def downcase_login
    self.login = self.login.downcase
  end

  def email
    self.login + "@lanzatech.com"
  end

  def get_name
    self.login.sub('.', ' ').split.map(&:capitalize).join(' ')
  end

  def get_name_link
    self.login.sub('.', '')
  end

  def add_user_group
    UserGroups.delay.some([self.login])
  end

  # Gets various metrics for user_show.
  def self.get_show_metrics(user, min_date, max_date, is_manager)

    requests = Request.where("updated_at >= ? AND updated_at <= ?", min_date, max_date)

    # Blank objects in case user isn't manager.
    non_manager_metrics = ActiveSupport::OrderedHash.new
    analysis = []

    if is_manager
      analysis = User.manager_analytics(min_date, max_date)
      non_manager_metrics["Total"] = []
      non_manager_metrics["Department"] = []
      non_manager_metrics["Total"] = User.user_analytics(requests)
      non_manager_metrics["Department"] = User.requests_by_group(requests)

      non_managers = User.where("admin = ? AND login != ? AND director = ?", true, user.login, false)
      non_managers.each do |non_manager|
        user_requests = requests.where("name = ? OR customer = ? OR assignment like ?", non_manager.login, non_manager.login, "%#{non_manager.login}%")
        non_manager_metrics[non_manager] = User.user_analytics(user_requests)
      end
    end

    user_requests = requests.where("name = ? OR customer = ? OR assignment like ?", user.login, user.login, "%#{user.login}%")
    user_metrics = User.user_analytics(user_requests)

    return non_manager_metrics, user_metrics, analysis
  end

  # Given two dates, return a number of results.
  def self.manager_analytics (min, max)
    analytics_list = {}

    if min != "" and max != ""
      min = min.to_datetime
      max = max.to_datetime

      # Before.
      before = Request.where("created_at <= ?", min)
      analytics_list["before_pending"] = before.where("status = ?", "Pending")
      analytics_list["before_ongoing"] = before.where("status = ?", "Ongoing")
      analytics_list["before_completed_in_period"] = before.where("updated_at >= ? AND updated_at <= ? AND status = ?", min, max, "Complete")

      # During.
      during = Request.where("created_at >= ? AND created_at <= ?", min, max)
      analytics_list["during_pending"] = during.where("status = ?", "Pending")
      analytics_list["during_ongoing"] = during.where("status = ?", "Ongoing")
      analytics_list["during_completed"] = during.where("status = ?", "Complete")

      # Totals.
      analytics_list["ongoing_pending"] = analytics_list["before_pending"].count + analytics_list["before_ongoing"].count + analytics_list["during_pending"].count + analytics_list["during_ongoing"].count
      analytics_list["completed"] = analytics_list["before_completed_in_period"].count + analytics_list["during_completed"].count
    end

    return analytics_list
  end

  # Returns requests launched and completed as well as data for per stage
  # and per request times over a set of requests.
  def self.user_analytics(requests)
    analytics_list = {}
    analytics_list["requests"] = requests
    analytics_list["requests_launched"] = analytics_list["requests"].length
    requests_completed = analytics_list["requests"].select { |x| x.status == "Complete" }
    analytics_list["requests_completed"] = requests_completed.length
    time_spent_per_request = []

    time_spent_per_stage = []

    requests_completed.each do |r|
      time_spent_per_request << [r.title, r.tothours, r.esthours]
      time_spent_per_stage << self.determine_pending_and_ongoing_times(r)
    end

    analytics_list["time_spent_per_request"] = time_spent_per_request
    analytics_list["time_spent_per_stage"] = time_spent_per_stage

    return analytics_list
  end

  # Determines the pending and ongoing times of a request.
  def self.determine_pending_and_ongoing_times(r)
    res = []
    res << r.title
    stathist = r.stathist
    pending = r.created_at.to_date

    begin
      ongoing = Date.parse stathist.match(/Ongoing:\s(\d+-\d+-\d+)/)[-1]
      res << (pending..ongoing).count

      complete = Date.parse stathist.match(/Complete:\s(\d+-\d+-\d+)/)[-1]
      res << (ongoing..complete).count
    rescue NoMethodError => exception
      res << 0
      res << 0
    end

    return res
  end

  # Creates a departmental breakdown of requests.
  def self.requests_by_group(requests)

    analytics_list = ActiveSupport::OrderedHash.new

    analytics_list["Synthetic Biology"] = 0
    analytics_list["Engineering"] = 0
    analytics_list["Process Engineering"] = 0
    analytics_list["Fermentation"] = 0
    analytics_list["Bioinformatics"] = 0
    analytics_list["Process Validation"] = 0
    analytics_list["CSO"] = 0
    customer_requests = requests.select { |x| x.customer.present? }
    analytics_list["Bioinformatics"] = requests.length - customer_requests.length
    customer_requests.each do |r|
      customer = User.where("login = ?", r.customer).first
      if customer.group
        analytics_list[User.where("login = ?", r.customer).first.group] += 1
      end
    end
    analytics_list.to_a
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :ldap_authenticatable, :rememberable, :trackable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    user = User.find(params[:id])

    # Checks if min/max dates are blank, sets defaults and sets them to date types.
    if params[:min].blank?
      params[:min] = (Date.today - 1.months)
    else
      params[:min] = params[:min].to_date
    end

    if params[:max].blank?
      params[:max] = Date.today
    else
      params[:max] = params[:max].to_date
    end

    is_manager = false

    if can? :manage, :all
      is_manager = true
    end

    non_manager_metrics, user_metrics, analysis = User.get_show_metrics(user, params[:min], (params[:max] + 1.day), is_manager)

    render locals: {
        user: user,
        non_manager_metrics: non_manager_metrics,
        user_metrics: user_metrics,
        analysis: analysis
    }
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_analysis.html.erb
<table class="table table-bordered">
	<tr class="active">
        <th colspan="2">Requests Before</th>
    </tr>
    <tr>
    	<td style="font-weight:bold" width="9%">Pending</td>
    	<td>
        <% analysis["before_pending"].each do |p| %>
            <%= link_to p.id, edit_request_path(p), 'data-toggle' => 'tool-tip', title: p.title %>
    		<% end %>
    	</td>
    </tr>
    <tr>
    	<td style="font-weight:bold" width="9%">Ongoing</td>
    	<td>
        <% analysis["before_ongoing"].each do |p| %>
            <%= link_to p.id, edit_request_path(p), 'data-toggle' => 'tool-tip', title: p.title %>
    		<% end %>
    	</td>
    </tr>
    <tr>
    	<td style="font-weight:bold" width="9%">Completed</td>
    	<td>
        <% analysis["before_completed_in_period"].each do |p| %>
            <%= link_to p.id, edit_request_path(p), 'data-toggle' => 'tool-tip', title: p.title %>
    		<% end %>
    	</td>
    </tr>

    <tr class="active">
        <th colspan="2">Requests During</th>
    </tr>
    <tr>
    	<td style="font-weight:bold" width="9%">Pending</td>
    	<td>
        <% analysis["during_pending"].each do |p| %>
            <%= link_to p.id, edit_request_path(p), 'data-toggle' => 'tool-tip', title: p.title %>
    		<% end %>
    	</td>
    </tr>
    <tr>
    	<td style="font-weight:bold" width="9%">Ongoing</td>
    	<td>
        <% analysis["during_ongoing"].each do |p| %>
            <%= link_to p.id, edit_request_path(p), 'data-toggle' => 'tool-tip', title: p.title %>
    		<% end %>
    	</td>
    </tr>
    <tr>
    	<td style="font-weight:bold" width="9%">Completed</td>
    	<td>
        <% analysis["during_completed"].each do |p| %>
            <%= link_to p.id, edit_request_path(p), 'data-toggle' => 'tool-tip', title: p.title %>
    		<% end %>
      </td>
    </tr>

    <tr class="active">
        <th>Ongoing and Pending</th>
        <th>Completed</th>
    </tr>
    <tr>
      <td><%= analysis["ongoing_pending"] %></td>
      <td><%= analysis["completed"] %></td>
    </tr>
</table>

app/views/users/_department_metrics.html.erb
<div class="row">
  <div class="col-md-12">
    <div id="department_request_makeup"></div>
  </div>
</div>

<script type="text/javascript">
  google.charts.load('current', {packages: ['corechart']});
  google.charts.setOnLoadCallback(drawDepartmentBreakdown);

  function drawDepartmentBreakdown() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', "Department");
    data.addColumn('number', "Requests")

    data.addRows(<%= raw user_metrics.to_json %>);

    var options = {
      title: 'Breakdown of all Requests by Department',
      width: $(window).width() * 0.50,
      height: $(window).width() * 0.25,
      pieSliceText: "none"
    };

    var chart = new google.visualization.PieChart(
        document.getElementById('department_request_makeup'));
    chart.draw(data, options);
  }
</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_manager.html.erb
<div class="row">
  <div class="col-md-12">
    <hr style="background-color:black;color:black;border-color:black">
    <h3> Manager Section </h3>
    <hr style="background-color:LightGray;color:LightGray;border-color:LightGray">
  </div>
</div>

<div class="row">
  <div class="col-md-12 bordered-tab-contents">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist" id="myTabs">
      <% non_manager_metrics.each do |user, value| %>
          <% if user == "Total" %>
              <li role="presentation" class="active">
                <a href="#Total" aria-controls="Total" role="tab" data-toggle="tab">Total</a>
              </li>
          <% elsif user == "Department" %>
              <li role="presentation">
                <a href="#Department" aria-controls="Department" role="tab" data-toggle="tab">Department</a>
              </li>
          <% else %>
              <li role="presentation">
                <a href="#<%= user.get_name_link %>" aria-controls="<%= user.get_name_link %>" role="tab" data-toggle="tab"><%= user.get_name %></a>
              </li>
          <% end %>
      <% end %>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content" id="tabs">
      <% non_manager_metrics.each do |user, value| %>
          <% if user == "Total" %>
              <div role="tabpanel" class="tab-pane active" id="Total">
                <%= render 'user_metrics', user_metrics: value, user_name_link: "Total", analysis: analysis %>
              </div>
          <% elsif user == "Department" %>
              <div role="tabpanel" class="tab-pane" id="Department">
                <%= render 'department_metrics', user_metrics: value, user_name_link: "Department" %>
              </div>
          <% else %>
              <div role="tabpanel" class="tab-pane" id="<%= user.get_name_link %>">
                <%= render 'user_metrics', user_metrics: value, user_name_link: user.get_name_link %>
              </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <hr style="background-color:LightGray;color:LightGray;border-color:LightGray">
  </div>
</div>

app/views/users/_user_metrics.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-bordered table-striped" id="user_table_<%= user_name_link %>">
      <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Submitted By</th>
        <th>Description</th>
        <th>Download Attachment</th>
        <th>Results</th>
        <th>Result Files</th>
        <th>Status</th>
        <th>Status History</th>
        <th>Job Assignment</th>
        <th>&nbsp;</th>
      </tr>
      </thead>
      <tbody>
      <% user_metrics["requests"].reverse.each do |request| %>
          <tr>
            <td><%= request.id %></td>
            <td><%= request.title %></td>
            <td>
              <%= request.get_name %>
              <% if request.customer? %>
                  <br/>(<%= User.where(:login => request.customer).first.get_name %>)
              <% end %>
            </td>
            <td style="white-space: pre-wrap;"><%= sanitize(request.description.to_s.force_encoding("UTF-8")) %></td>
            <td>
              <% request.data_files.each do |p| %>
                  <%= link_to truncate("#{p.attachment_uploader_url.split("/").last}", :length => 20), p.attachment_uploader_url, {:title => "#{p.attachment_uploader_url.split("/").last}"} %>
                  <br/>
              <% end %>
            </td>
            <td style="white-space: pre-wrap;"><%= sanitize(request.result.to_s.force_encoding("UTF-8")) %></td>
            <td>
              <% request.result_files.each do |p| %>
                  <%= link_to truncate("#{p.attachment_uploader_url.split("/").last}", :length => 20), p.attachment_uploader_url, {:title => "#{p.attachment_uploader_url.split("/").last}"} %>
                  <br/>
              <% end %>
            </td>
            <% if request.status == "Complete" %>
                <td style="background-color:#4CAE4C;color:white"><%= request.status %></td>
            <% elsif request.status == "Ongoing" %>
                <td style="background-color:#46B8DA;color:white"><%= request.status %></td>
            <% else %>
                <td style="background-color:#EEA236;color:white"><%= request.status %></td>
            <% end %>
            <td><%= simple_format(request.stathist) %></td>
            <td><%= request.get_users_for_view %></td>
            <td>
              <% if current_user.nil? || request.name == current_user.login || current_user.admin %>
                  <%= link_to "Edit", edit_request_path(request), class: "btn btn-default" %>
                  <%= button_to "Delete", request, method: :delete, class: "btn btn-default", data: {confirm: "Are you sure that you wish to delete #{request.title}?"} %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <hr style="background-color:LightGray;color:LightGray;border-color:LightGray">
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h4>Projects Launched: <%= user_metrics["requests_launched"] %> </h4>
    <h4>Projects Completed: <%= user_metrics["requests_completed"] %> </h4>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div id="time_spent_per_request_<%= user_name_link %>"></div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div id="time_spent_per_stage_<%= user_name_link %>"></div>
  </div>
</div>

<script type="text/javascript">
  google.charts.load('current', {packages: ['corechart', 'bar']});
  main_div = document.getElementById('time_spent_per_request_<%= user_name_link %>');
  google.charts.setOnLoadCallback(drawCompletedRequests);
  google.charts.setOnLoadCallback(drawCompletedStages);

  function drawCompletedRequests() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Request Title');
    data.addColumn('number', 'Total Hours');
    data.addColumn('number', 'Estimated Hours');

    data.addRows(<%= raw user_metrics["time_spent_per_request"].to_json %>);

    var options = {
      title: 'Time Spent per Completed Request',
      hAxis: {
        title: 'Request Title', showTextEvery: 1, textStyle: {fontSize: 14.5}, titleTextStyle: {fontSize: 17.5}
      },
      vAxis: {
        title: 'Hours'
      },
      colors: ['#428bca', '#46B8DA'],
      width: $(window).width() * 0.95
    };

    var chart = new google.visualization.ColumnChart(
        document.getElementById('time_spent_per_request_<%= user_name_link %>'));
    chart.draw(data, options);
  }

  function drawCompletedStages() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Request Title');
    data.addColumn('number', 'Pending to Ongoing');
    data.addColumn('number', 'Ongoing to Complete');

    data.addRows(<%= raw user_metrics["time_spent_per_stage"].to_json %>);

    var options = {
      title: 'Days Spent per Stage',
      isStacked: true,
      hAxis: {
        title: 'Request Title', showTextEvery: 1, textStyle: {fontSize: 14.5}, titleTextStyle: {fontSize: 17.5}
      },
      vAxis: {
        title: 'Days'
      },
      colors: ['#EEA236', '#46B8DA'],
      width: $(window).width() * 0.95
    };

    var chart = new google.visualization.ColumnChart(
        document.getElementById('time_spent_per_stage_<%= user_name_link %>'));
    chart.draw(data, options);
  }
</script>

<div class="row">
  <div class="col-md-12">
    <hr style="background-color:LightGray;color:LightGray;border-color:LightGray">
  </div>
</div>

<% if user_name_link == "Total" %>
    <div class="row">
      <div class="col-md-12">
        <%= render 'analysis', analysis: analysis %>
      </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_tag(user_path(user), :method => "get", class: "form-inline") do %>
        <div class="form-group">
          <div class="input-daterange input-group" id="datepicker" data-provide="datepicker" data-date-format="yyyy-mm-dd" data-date-todayHighlight="1">
            <%= text_field_tag :min, params[:min], type: "text", class: "form-control", id: "date_min" %>
            <span class="input-group-addon">to</span>
            <%= text_field_tag :max, params[:max], type: "text", class: "form-control", id: "date_max" %>
          </div>
        </div>
        <div class="form-group">
          <%= select_tag "specific_dates", options_for_select([["Select Preset", ""], ['1 Month', '1 Month'], ['3 Months', '3 Months'], ['6 Months', '6 Months'], ['1 Year', '1 Year']]), class: "form-control" %>
        </div>
        <div class="form-group">
          <%= submit_tag "View", class: "btn btn-default" %>
        </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <hr style="background-color:LightGray;color:LightGray;border-color:LightGray">
  </div>
</div>

<%= render 'user_metrics', user_metrics: user_metrics, user_name_link: user.get_name_link %>

<% if (can? :manage, :all) %>
    <%= render 'manager', non_manager_metrics: non_manager_metrics, analysis: analysis %>
<% end %>