config/routes.rb
Rails.application.routes.draw do
  get "requests/edit", :to => "requests#index"
  get "requests/show", :to => "requests#index"
  get "requests/update", :to => "request#index"
  devise_scope :user do
    get "/users/sign_up",  :to => "requests#index"
  end

  devise_for :users
  resources :requests, only: [:index, :new, :create, :destroy, :update, :edit]
  resources :users, only: [:show]

  root "requests#index"

end

app/models/request.rb
class Request < ApplicationRecord
  before_save :set_stathist, :handle_est_hours
  has_paper_trail
  validates :name, presence: true # Make sure the owner's name is present.
  validates :title, presence: true
  validates_with OngoingValidator
  validates_presence_of :esthours, :if => lambda { self.status == "Ongoing" }
  validates_presence_of :tothours, :if => lambda { self.status == "Complete" }
  has_many :data_files
  has_many :result_files
  accepts_nested_attributes_for :data_files, :allow_destroy => true
  accepts_nested_attributes_for :result_files, :allow_destroy => true
  serialize :current_changes
  serialize :assignment

  # Get priority items for modal. 
  def self.priority_widget
    pending = Request.where("status = ?", "Pending").order! 'created_at DESC'
    high_p = pending.where("priority = ?", "High Priority")
    normal_p = pending.where("priority = ?", "Priority")
    low_p = pending.where("priority = ?", "Low Priority")
    time_perm = pending.where("priority = ?", "Time Permitting")
    return priority_list = {
        "high" => high_p,
        "normal" => normal_p,
        "low" => low_p,
        "time_permitting" => time_perm
    }
  end

  # Get ongoing requests.
  def self.active_requests
    ongoing_requests = ActiveSupport::OrderedHash.new
    max_length = 1
    User.where("admin = ?", true).each do |user|
      requests = Request.where("(name = ? OR customer = ? OR assignment like ?) AND status = ?", user.login, user.login, "%#{user.login}%", "Ongoing").sort_by &:updated_at
      if requests.length > max_length
        max_length = requests.length
      end
      ongoing_requests[user.get_name] = requests
    end
    return ongoing_requests, max_length
  end

  #
  def handle_est_hours
    if self.tothours and not self.esthours
      self.esthours = self.tothours
    end
  end

  # Updates the versioning for the status.
  def set_stathist
    stats = ["Pending", "Ongoing", "Complete"]
    if self.stathist.nil? or self.status_changed?
      res = ""
      stats.each do |sta|
        if sta == self.status
          if self.stathist.nil?
            self.stathist = res + sta + ": " + Date.today.to_s + "\n"
          else
            self.stathist += res + sta + ": " + Date.today.to_s + "\n"
          end
          return
        elsif self.stathist.nil? or not self.stathist.include? sta
          res += sta + ": " + Date.today.to_s + "\n"
        end
      end
    end
  end

  # Gets users in a view ready format. Adds captitalisation etc.
  def get_users_for_view(assignment = self.assignment)
    if assignment
      Array(assignment).map { |a| get_name(a) }.reject { |c| c.empty? }.join(", ")
    end
  end

  def get_name(name = self.name)
    name.sub('.', ' ').split.map(&:capitalize).join(' ')
  end

  # Determines whether a true edit has been made, as opposed
  # to just a modified or updated change.
  def check_for_edits_email
    latest_version = get_versions[0]
    number_of_edits_total = latest_version.lines.count
    number_of_edits_non_essential = 1 #0 + 1 to ignore updated_at

    if number_of_edits_total - number_of_edits_non_essential > 0
      return true
    else
      return false
    end
  end

  def send_edit_email
    changes = self.get_changed_attributes
    if changes != self.current_changes
      Emailer.edit_request(self.id).deliver_later!
    end
    self.update_column(:current_changes, changes.to_yaml)
  end


  # Returns changes from papertrail, minus the excepted ones.
  def get_changed_attributes
    return self.versions.last.changeset.except("updated_at", "created_at", "stathist")
  end

  # Gets all versions for form view.
  def get_versions
    versions = []
    self.versions.reverse.each do |version|
      versions << cleanup_version_html(version.changeset)
    end
    return versions
  end

  # Gets last version.
  def get_version_latest
    return cleanup_version_html(get_changed_attributes)
  end

  # Converts versions to HTML readable format.
  def cleanup_version_html (version)
    cleaned_version = ''
    version.each do |key, changes|
      prev_version = changes.first
      curr_version = changes.last
      if key == "assignment"
        prev_version = self.get_users_for_view prev_version
        curr_version = self.get_users_for_view curr_version
      end
      if prev_version.nil? || prev_version.to_s.empty?
        prev_version = 'NO VALUE'
      elsif curr_version.nil? || curr_version.to_s.empty?
        curr_version = 'NO VALUE'
      end
      cleaned_version += "<h4>" + key.capitalize.scrub + ':</h4> ' + prev_version.to_s.scrub + ' <b> => </b> ' + curr_version.to_s.scrub
    end
    return cleaned_version + "<hr>"
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
    respond_to do |format|
      format.html {
        priority_modal = Request.priority_widget
        active_requests, max_length = Request.active_requests
        render locals: {
            priority_modal: priority_modal,
            active_requests: active_requests,
            max_length: max_length
        }
      }
      format.json { render json: RequestDatatable.new(view_context, {current_user: current_user}) }
    end
  end

  def new
    @request = Request.new
  end

  def create
    params.permit!
    @request = Request.new(request_params)

    @request.name = current_user.login
    if @request.save
      # Emails are placed Async.
      unless params[:dont_send_emails]
        Emailer.new_request(@request.id).deliver_later!
      end

      DataFile.save_data_files(params[:data_files], params[:data_files_delete], @request)
      ResultFile.save_result_files(params[:result_files], params[:result_files_delete], @request)

      redirect_to requests_path, notice: "The request #{@request.title} has been created."
    else
      render "new"
    end
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to requests_path, notice: "The request #{@request.title} has been deleted."
  end

  def edit
    @request = Request.find(params[:id])
  end

  def update
    params.permit!
    @request = Request.find(params[:id])
    if @request.update_attributes(request_params)
      # The email send logic is contained within each edit type, as to 
      # avoid sending emails where no changes have occured. 
      unless params[:dont_send_emails]
        @request.send_edit_email
      end
      DataFile.save_data_files(params[:data_files], params[:data_files_delete], @request)
      ResultFile.save_result_files(params[:result_files], params[:result_files_delete], @request)

      redirect_to requests_path, notice: "The request #{@request.title} has been updated."
    else
      render 'edit'
    end
  end

  # Allowed params include nested attachments, results, and employee names. 
  private
  def request_params
    params.require(:request).permit(:name, :title, :description, :status, :stathist, :customer, :priority, :esthours, :tothours, :result, {:assignment => []}, data_files: [:id, :request_id, :attachment_uploader, :_destroy], result_files: [:id, :request_id, :attachment_uploader, :_destroy])
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
  def sanatize_wysihtml text
    allowed_tags = (Loofah::HTML5::WhiteList::ALLOWED_ELEMENTS_WITH_LIBXML2.add(%w['u','font']))
    default_attributes = Loofah::HTML5::WhiteList::ALLOWED_ATTRIBUTES.add('face')
    utf8_text = text.to_s.force_encoding("UTF-8")
    sanitize utf8_text, tags: allowed_tags, attributes: default_attributes
  end
end

app/views/requests/_active.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>
      <h3 class="modal-title">Ongoing Requests</h3>
    </div>
    <div class="modal-body">
      <div style="overflow-x:auto;">
        <table class="table table-bordered">
          <tr>
            <th>User</th>
            <th colspan="<%= max_length %>">Ongoing Requests (Sorted by Most Recent)</th>
          </tr>
          <% active_requests.each do |user, requests| %>
              <tr>
                <td><%= user %></td>
                <% requests.each_with_index do |r, i| %>
                    <td>
                      <%= link_to truncate(r.title, :length => 15), edit_request_path(r), 'data-toggle' => 'tool-tip', title: r.title %>
                    </td>
                <% end %>
                <% if requests.length < max_length %>
                    <% (max_length - requests.length).times do |n| %>
                        <td></td>
                    <% end %>
                <% end %>
              </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/requests/_priority.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h3 class="modal-title">Priority Requests</h3>
    </div>
    <div class="modal-body">
      <table class="table table-bordered">
        <tr class="active">
          <th colspan="2">High Priority</th>
        </tr>
        <% priority_modal["high"].each do |p| %>
          <tr>
            <td><%= link_to truncate(p.title, :length => 15), edit_request_path(p), 'data-toggle' => 'tool-tip', title: p.title %></td>
            <td><%= p.created_at.to_date %></td>
          </tr>
        <% end %>

        <tr class="active">
          <th colspan="2">Priority</th>
        </tr>
        <% priority_modal["normal"].each do |p| %>
          <tr>
            <td><%= link_to truncate(p.title, :length => 15), edit_request_path(p), 'data-toggle' => 'tool-tip', title: p.title %></td>
            <td><%= p.created_at.to_date %></td>
          </tr>
        <% end %>

        <tr class="active">
          <th colspan="2">Low Priority</th>
        </tr>
        <% priority_modal["low"].each do |p| %>
          <tr>
            <td><%= link_to truncate(p.title, :length => 15), edit_request_path(p), 'data-toggle' => 'tool-tip', title: p.title %></td>
            <td><%= p.created_at.to_date %></td>
          </tr>
        <% end %>

        <tr class="active">
          <th colspan="2">Time Permitting</th>
        </tr>
        <% priority_modal["time_permitting"].each do |p| %>
          <tr>
            <td><%= link_to truncate(p.title, :length => 15), edit_request_path(p), 'data-toggle' => 'tool-tip', title: p.title %></td>
            <td><%= p.created_at.to_date %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/requests/_request_form.html.erb
<div class="request_form">
  <% if !@request.errors.empty? %>
      <div class="alert alert-error">
        <ul>
          <% @request.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
  <div class="well" style="margin-top:10px">
    <%= nested_form_for @request, html: {multipart: true} do |f| %>
        <form>
          <div class="form-group">
            <%= f.label :title %>
            <div class="row">
              <div class="col-md-4">
                <%= f.text_field :title, class: "form-control", type: 'text' %>
              </div>
            </div>
          </div>
          <%= f.hidden_field :name %>
          <div class="form-group">
            <%= f.label :description %>
            <div class="row">
              <div class="col-md-4">
                <%= f.text_area :description, class: "form-control summernote", type: 'text', id: 'summernote' %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-md-4">
                <%= f.label :priority %>
                <%= f.select :priority, [['Time Permitting', 'Time Permitting'], ['Low Priority', 'Low Priority'], ['Priority', 'Priority'], ['High Priority', 'High Priority']], {}, {class: 'form-control'} %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :attachment_uploader, 'Attachments [Submit to save file(s)]' %><br/>
            <%= f.file_field :attachment_uploader, :multiple => true, name: "data_files[attachment_uploader][]", type: 'file' %>
            <br/>
            <% unless @request.data_files.empty? %><br/>
                <%= f.label :attachment_uploader, 'Current Attachments:' %><br/>
            <% end %>
            <%= f.fields_for :data_files do |attachment| %>
                <% if !attachment.object.new_record? %>
                    <%= attachment.label :attachment_uploader, 'Delete: ' + attachment.object.attachment_uploader_url.split("/").last %>
                    <%= check_box_tag "data_files_delete[]", attachment.object.id, checked = false %>
                <% end %>
            <% end %>
          </div>

          <% if (can? :read, request) || current_user.nil? %>
              <hr style="background-color:black;color:black;border-color:black">
              <div class="form-group">
                <%= f.label :status %>
                <div class="row">
                  <div class="col-md-4">
                    <%= f.select :status, [['Pending', 'Pending'], ['Ongoing', 'Ongoing'], ['Complete', 'Complete']], {}, {class: 'form-control'} %>
                  </div>
                </div>
              </div>
              <div class="form-group" id="esthours_div" style="display: none;">
                <%= f.label :esthours, "Estimated Hours" %>
                <div class="row">
                  <div class="col-md-4">
                    <%= f.text_field :esthours, class: 'form-control', type: 'number' %>
                  </div>
                </div>
              </div>
              <div class="form-group" id="tothours_div" style="display: none;">
                <%= f.label :tothours, "Total Hours" %>
                <div class="row">
                  <div class="col-md-4">
                    <%= f.text_field :tothours, class: 'form-control', type: 'number' %>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :assignment %>
                <div class="row">
                  <div class="col-md-4">
                    <%= f.select :assignment, options_from_collection_for_select(User.where(:admin => true), :login, 'get_name', {:selected => @request.assignment}), {}, {:multiple => true, :name => 'request[assignment][]', class: 'form-control'} %>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :customer %>
                <div class="row">
                  <div class="col-md-4">
                    <%= f.select :customer, options_from_collection_for_select(User.where(:admin => false), :login, 'get_name', {:selected => @request.customer}), {include_blank: true}, {class: 'form-control'} %>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :result %>
                <div class="row">
                  <div class="col-md-4">
                    <%= f.text_area :result, class: "form-control summernote", type: 'text' %>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :attachment_uploader, 'Results [Submit to save file(s)]' %><br/>
                <%= f.file_field :attachment_uploader, :multiple => true, name: "result_files[attachment_uploader][]", type: 'file' %>
                <br/>
                <% unless @request.result_files.empty? %><br/>
                    <%= f.label :attachment_uploader, 'Current Results:' %><br/>
                <% end %>
                <%= f.fields_for :result_files do |attachment| %>
                    <% if !attachment.object.new_record? %>
                        <%= attachment.label :attachment_uploader, 'Delete: ' + attachment.object.attachment_uploader_url.split("/").last %>
                        <%= check_box_tag "result_files_delete[]", attachment.object.id, checked = false %>
                    <% end %>
                <% end %>
              </div>
          <% end %>
          <div class="checkbox-inline">
            <label>
              <%= check_box_tag(:dont_send_emails, params[:dont_sent_emails], checked = false) %> Don't send email
            </label>
          </div>
          <br/>
          <%= f.submit "Submit", class: "btn btn-default" %>
          <%= link_to 'Cancel', :root, class: "btn btn-warning" %>
          <hr style="background-color:black;color:black;border-color:black">
          <a href="#versions_div" onclick="toggle_visibility('versions_div');"><h3>Versions:</h3></a>
          <div id="versions_div" style="display:none;">
            <% @request.get_versions.each do |v| %>
                <% begin %>
                    <td style="white-space: pre-wrap;"><%= sanitize(v.to_s.force_encoding("UTF-8")) %></td>
                <% rescue %>
                    <td style="white-space: pre-wrap;">FORMAT ERROR</td>
                <% end %>
            <% end %>
          </div>
        </form>
    <% end %>
  </div>
</div>

app/views/requests/backup_request_form.html.erb
<div class="request_form">
<% if !@request.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="well">
<img src="/assets/BurP.png">
  <%= nested_form_for @request, html: { multipart: true }, class: 'form-inline' do |f| %>
  	<%= f.label :title, class: 'mandatory' %><br />
    <%= f.text_field :title %><br /><br />
    <%= f.hidden_field :name %> 
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => "50x10" %><br /><br />
    <%= f.label :attachment_uploader, 'Attachments' %><%= f.file_field :attachment_uploader, :multiple => true, name: "data_files[attachment_uploader][]" %><br />
    <% unless @request.data_files.empty? %>
      <%= f.label :attachment_uploader, 'Current Attachments:' %><br />
    <% end %>
    <%= f.fields_for :data_files do |attachment| %>
      <% if !attachment.object.new_record? %>
        <%= attachment.label :attachment_uploader, 'Delete: ' + attachment.object.attachment_uploader_url.split("/").last %>
        <%= attachment.check_box :_destroy %>
      <% end %>
    <% end %>

    <% if can? :read, request %>
      <br />
      <%= f.label :status %><br />
      <%= f.select :status, [['Pending','Pending'],['Ongoing','Ongoing'],['Complete','Complete']] %><br /><br />
      <%= f.label :assignment %><br />
          <%= f.select :assignment, options_from_collection_for_select(User.where(:admin => true), :login, 'get_name', {:selected => @request.assignment}), {}, {:multiple => true, :name => 'request[assignment][]'} %>
          <br/><br/>
      <%= f.label :customer %><br />
      <%= f.select :customer, options_from_collection_for_select(User.where(:admin => false), :login, 'get_name', {:selected => @request.customer}), { include_blank: true }%><br /><br />
      <%= f.label :result %><br />
      <%= f.text_area :result, :size => "50x10" %><br /><br />
      <%= f.label :attachment_uploader, 'Results' %><%= f.file_field :attachment_uploader, :multiple => true, name: "result_files[attachment_uploader][]" %><br />
      <% unless @request.result_files.empty? %>
         <%= f.label :attachment_uploader, 'Current Results:' %><br />
      <% end %>
      <%= f.fields_for :result_files do |attachment| %>
        <% if !attachment.object.new_record? %>
          <%= attachment.label :attachment_uploader, 'Delete: ' + attachment.object.attachment_uploader_url.split("/").last %>
          <%= attachment.check_box :_destroy %>
        <% end %>
      <% end %>
    <% end %>
    <br />
    <%= f.submit "Submit", class: "btn btn-default" %>
    <%= link_to 'Cancel', :root, class: "btn btn-warning" %>
    <br /><br />
    <hr style="background-color:black;color:black;border-color:black">
    <%= f.label :version, 'Versions:' %>
    <% @request.get_versions.each do |v| %>
     <td style="white-space: pre-wrap;"><%= simple_format(v) %></td>
    <% end %>
  <% end %>
</div>
</div>

app/views/requests/create.html.erb
<h1>Requests#create</h1>
<p>Find me in app/views/requests/create.html.erb</p>

app/views/requests/destroy.html.erb
<h1>Requests#destroy</h1>
<p>Find me in app/views/requests/destroy.html.erb</p>

app/views/requests/edit.html.erb
<%= render(partial: "request_form", object: @request) %>

app/views/requests/index.html.erb
<div class="row" style="text-align: center;">
  <div class="col-md-12">
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#priority_modal">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    </button>
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#active_modal">
      <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
    </button>
    <%= link_to "New bioinformatics request", new_request_path, class: "btn btn-default btn-lg " %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="modal fade" id="priority_modal" tabindex="-1" role="dialog" aria-labelledby="Priority Requests" aria-hidden="true">
      <%= render 'priority', priority_modal: priority_modal %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="modal fade" id="active_modal" tabindex="-1" role="dialog" aria-labelledby="Active Requests" aria-hidden="true">
      <%= render 'active', active_requests: active_requests, max_length: max_length %>
    </div>
  </div>
</div>

<br/>

<div class="row">
  <div class="col-md-12">
    <table id="requests-table" data-source="<%= requests_path(format: :json) %>" class="table table-bordered table-striped">
      <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Submitted By</th>
        <th>Description</th>
        <th>Download Attachment</th>
        <th>Results</th>
        <th>Result Files</th>
        <th>Status</th>
        <th>Status History</th>
        <th>Priority</th>
        <th>Job Assignment</th>
        <th>&nbsp;</th>
      </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>

<div class="row" style="text-align: center;">
  <div class="col-md-12">
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#priority_modal">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    </button>
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#active_modal">
      <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
    </button>
    <%= link_to "New bioinformatics request", new_request_path, class: "btn btn-default btn-lg " %>
  </div>
</div>

app/views/requests/new.html.erb
<%= render(partial: "request_form", object: @request) %>

app/views/requests/show.html.erb
<h1>Requests#show</h1>
<p>Find me in app/views/requests/show.html.erb</p>

app/views/requests/update.html.erb
<% if !@request.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
 
<div class="well">
  <%= form_for @request, html: { multipart: true } do |f| %>
  	<%= f.label :title %><br />
    <%= f.text_field :title %><br /><br />
    <%= f.label :name %><br />
    <%= f.text_field :name %><br /><br />
    <%= f.label :description %><br />
    <%= f.text_area :description %><br /><br />
    <%= f.label :attachment %><%= f.file_field :attachment %><br />
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>